# Generated by Django 4.0.6 on 2022-07-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earlshorten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
